---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: git-creds
  namespace: argocd
spec:
  encryptedData:
    password: AgBjYXKKfcRHdDeYrIPsjXu5AmchEV8prAjVBVKIdLyUSXYcrzC+12fx4OwRhUxte7KtocgfKtU4J5LWcqjAwdNA6D7jfcyzL6ng3bXfB69PKs8K+VoSbLeJmp/NjXDksssF5cCYDO2NXGmWefz9Gbh9wKqim8lFLcBJmzMG6mMrEekCKn1jJ3xKVb6NsxQYvOo4TA5qBRDDKKW1pWNjF7iSG0IULh2ohuUuTuooPRr0HbfJCJirUiA/gpzMPyIUNl39ZqReE1qsqRF5ourjrcKjiJ7qWyL68akGIZIUP0IEaYpSWZqY53WpSga1IQw6v2Vqd4hBXIbBTZze8jcqTl4FHJdipBEkOt5fASucEwdVtf7tYfAPvDDlB1ujG19BNOwONh66UQz1unPooZWhyAIFD58dav4M1NV7OXhaCnEhI/w8/Z/gKXEA5uU69klWL4kNYiMM+10BNWlwSbOcdJ7Iahy7ENwSH/u+miBr6D5OzwqDdgVHZXcJ/XnGhMME4rzVbiot9mJSfh5dTmOGqGb+k8mikv3J5miCIv9YttzdgEKDMRREor8CaxwsnEUQd6YUEfwmZ1a5miKgtdglNPvJTumBX3tktCBs6JRMh4Cpz6etrp9rn81INFL43aDMdMlmEtjj6D3DmxbIew+GBiAg/dOiiyPm43vgy3MjrRKLZtvPJgMmj8D+4iirqmlyMU4oFoA3pEwdkl0HSO01bFv/AYWeQ9xRLV4oaRw7E7nFu3IgFuOmAZuXpEVrIVPdRwYoDwpI+/BDvEqYiljAwPYhc4nwlpDdbRR/IwXgnMal5ZdTFVG+/FW3aBIu0gA=
    username: AgBlBST8ge+++jQvVUJ9mQAIgMJZplPK/tBG8LnQi1UOeJP/Nf9MGQtLLbTOPlnc9KPDeHw4z5W8UjhaojE6dn3WrwaZOSWsUd/o608DT4FnvbARJdVED7Wcfs0KQd3bRcHrGRxZrWr+A5b7zQRTkYuaAFBlKg4jt/F7uuzbWXWpeSSo50coc1psCAlqT2t2PeQjJrOxJQ9WyY2Jt3lAHYLXcnEnyHrhkNrY3WvcWK4/xFfYU0zCNohf63DTIdxs3om+yzLaYTEE2gmz563uscRQScZE1iIm+OntuPJJ4YWTZP0uTOyEcA+urY10xwA2jQHuJYUbQ9l4eunLyYrB/FnKX+4cIfOi55Ng1DyWJJGXxhDSIWloK79gICwkX62SdcIBeaDJmBQLv0YnbQT9DXbd7jK1aPaPBp3XUx6u4z2XPOWjCdhwN1u044+AQE7/7Q/go+xMMDsnu8MF/bsVKkVX34flXcOYnBwxymiRz8tpX7MGxyDzExE0mNvBmaC2QiMrkpT2xMdFTx2HIqWzNPSBDE/D2FFiQ5p5ZpMWrKgobneDJMfPZ6OXsWwNZBrXwW2iBzMEHqu2LDKcdZN3tIDF6fd54hdNtooeS0LRD/OzU1NEZW3V87nZTqMEIjfp2hvnHYPf0KxCX0kke/00OPVvoifUD9GZfikw2LE9kuq8d3xnMgE4TGF+eAYMxEq/iupIPKBlGRRA5Dw=
  template:
    metadata:
      name: git-creds
      namespace: argocd
