apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: solutio-prod
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml
  - migrate-job.yaml
  - seed-job.yaml
images:
  - name: ghcr.io/toyinogun/rms
    digest: sha256:8072de71bb129754503a33693f6017e8acd813cc44474ee95ed4b37be6cbe2b3
    newTag: main
  - name: ghcr.io/toyinogun/rms-migrate
    digest: sha256:2f1d5390355da9c3b0e46064eba8107d989423d7b4166444ae20c0a74595ddf9
    newTag: main
