apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: solutio-prod
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml
  - migrate-job.yaml
  - seed-job.yaml
images:
  - name: ghcr.io/toyinogun/rms
    digest: sha256:e15b74c3e034038262295f9d885cbc0e69cafc5a5b3d1a346c1e68130c6a9a3e
    newTag: main
  - name: ghcr.io/toyinogun/rms-migrate
    digest: sha256:4765f656ab32daa1c697327c5fb55280f67b2710eea3b7b29194b0ff2691d9bf
    newTag: main
