apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: solutio-prod
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml
  - migrate-job.yaml
  - seed-job.yaml
images:
  - name: ghcr.io/toyinogun/rms
    digest: sha256:52806d40851adf7aa7a31b01fccf0e9593ce24fbcca730f96c4ffff0af077aea
    newTag: main
  - name: ghcr.io/toyinogun/rms-migrate
    digest: sha256:7093302b07534584c41f9817a8ce3c3bd934d66ff7f1f38d9397725eccd13414
    newTag: main
