apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: solutio-prod
resources:
  - solutio-db.sealedsecret.yaml
  - solutio-auth.sealedsecret.yaml
  - solutio-seed.sealedsecret.yaml
