---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: solutio-db
  namespace: solutio-prod
spec:
  encryptedData:
    DATABASE_URL: AgBk5jzBMjl+BpWlaBAyT8ybbuBBJ0ES2cyj6PtmC9qbB/1oQ5m270yc9twMUX/H4Fm/60UwgIpPgNVlfmIFGHtmAOOcphXNrXko9HqyqSWZ1Sn9dA7dkd0o0NfCiu/Y45lIlUDnRWysWkTNlAjCyd5uX21OrqqnGac3pXDLG1dwadHvWKWYRcHUele0Nx9gDhfLZ0Tp8Njn/z3SIRIN/22TptD4ZClmVKcYK0ZEDH+aPoy7wynfEGkoEohLlTGs/yrZxa9C1PiBIN6bqO6jXaWh+chFV3ngW/Aqb9/iikwHRuBzgvW++tSKbTFoa+URiRC6r+qHglTXhXIL+hshWOiI0GTW59IMencUHkFh8TV8HQhpzxQ4bQLrh2tuNCrSGM8dJTnpkQz33uuz0bHy7Pmp1QGLX4fs2y6dlv8pcfyW2Mx7yzYx8eUYNzKuYrjE6ZFU46gEbvo+Jkdjsc5x63zwquaQx8XklpUtmf6cfKQ7+ssgsVMv8yV+6G5etFhndizXOSsNd57FFUwNt8kmtZ15bxrTTf7ySWs9t/oW5M3U4pnRXxxnJ+s3eflHL4U827B7vDS5yW7U1WFiQZfFuDw/3Qh8TeL2za1OGbDV46KUtUQk61HEIfbZcgXnK/qV7XhQCrOW84t4IjvxyRlQHuCyTF7vmOMbv7sUBPr7fLq3afjm2RRzc2XmR33T6b2XD9E86yaOEaOWHroxvu4muix8RE/IfoVVKOK13G8/5+qBiLnc2ctR1ScoRovtGWGcy4or3tFC8HPj5CIn8KnwUe0m9zGITdJZQeSbo9UPrW+f2XGDwarLr9D+/fsPzV9XFv6hWagcWC0ogJt5ehTPcRuMmdkf9tA5jGDFVb/pyHab11Kp+pTapvcH0oSM9aHTGtmd+xwddJ+l0Y+xV3H+
  template:
    metadata:
      name: solutio-db
      namespace: solutio-prod
    type: Opaque
