---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: solutio-auth
  namespace: solutio-prod
spec:
  encryptedData:
    BETTER_AUTH_SECRET: AgB57BtkEmhw6Tc9DGJRyf2EhIjeAJcNMWfJe5gTwzCR1m9hKPHg1P2F2ua4lwi7ua3i2MNMni4YEzV6tFSqkuDbyDS8re5ybSimgwf2RJjJzZPPRqlfKKjkAQLjeaehMCQkeUos8ZczUsuZtsqhbZZDOa2RtQFnO0HdQc4HPQRLz9FMOpqKXAKrdKooWo0EEBCpGsJPaWXnwrdr8l7QlZVdDME3oDQZYpqN9f0dLoDkD3tFdcZaYu9Au3fuBV/IfCTDNXgjCa8JKUTdp6uKUu8Sl0UCGESa0TT0LttEC7qvbqiTYk52bJ5YpW93FXLB3dsu326KVC25I2t3E8AsSnlimeOMk9kc9UuAl3j5Uyd1+yi0XJGwoVH7t0RPMaCoN4KwkzNrsSVHhEn6BS937EVtBqotG4JgExiffvyLupYzLrp4HR8w/dteLt+iyNNMKFA7DoSM5invRw632bwPrcrzCg+ur1rFmOqXDZM2bRrzcMz9n3B6HlpKxYk408ocV4lM23mCdvHGefz8qDrNvdkEvGfxUVsipH6AWDtQ6Op3m3DRt15iA3Pj14kWnSeP8Ae+wkyNT/nr+Xt3UocLloZWnPW4ijf1eWyv7fVAxKktlO0EkG0P3FzAK2niHbJCrtrTmRq7YHf7pY1KXPF14yw9Vd0PN8OFZWSIoMJgNIdBs1QlD0O3ooW2r2nyL5EiwX2yBvNYE5KuNFFgNim9HkMFks2LfiLpkm1CDWNh7tM5MYJse7BojFBnDqskq1dUJodjRk43xlyVnH13atXih9ck
    BETTER_AUTH_URL: AgAVjc3aNrOrelYA68ynrMT1w5i6MassB27adtgYlhBry6XFnYbYUedw4U+EGfbqsDErEFr698EBEgSnha74NmQljSS7ER5T7LUvXYe6wwFzbMLZtDexfsT76rYgJqS//LepTSWussktIj8d03d6LTj0TVna0703IqRcJ4jZs2AWwthhGQmSCV3IcetUrCxlPIENJR/DnlXWyNd6OlhI0mkl/tC+FtgbtWxx0Rqa6bs5tWsKAAKIPkAvrKjvyAK5o3kxJk+GphJC0g8TDawH3rN212r6a205U5obc9mxwL8qoBAZlgQih1TCsctLxnzc5bEaPQWmVeoBIoqyKw6zqYB/I1dXI9K2yT+0rEP8kqaQPz1Z+JQWRUMgzk5Qvddf8gOUDKu+i/qMFs1ulsesy0cqFzyZVThRqEZdamhPZ6fmx+gekQ4+rLzaL7qneQda596U2nYyToh4EvjZkzvrXRJ/k3WM8Z4FBLrTiOpBmFAUX+mSjUhxAKAQJeP2oj5zgRlZI0n+lVfFvwb6xMcDC2EMV2XmtI0iq1ELPOSHceadNW6MG1E9LQOkY/rQzpgNI9UBPYV60mJtuMmP64a6inZ6B2ZTnyL2SPvtKAIzXmW+Jqq4lb8aamCq7XJMO8KRhXxMCPjmHnZRlvNdsuvnlJhSzerlsfyZLSNwyjdh9xLtwNHGwt2ORrKBS15oISJ6Pa8ACuGC6qrFUWSKGXoPJCMtk72aN2y+fvQdaKIAgQ==
  template:
    metadata:
      name: solutio-auth
      namespace: solutio-prod
    type: Opaque
