---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: solutio-db
  namespace: solutio-prod
spec:
  encryptedData:
    DATABASE_URL: AgBZIrMKVUtzgjqUVSen81nx3Y9HFVaRP1WJqgWzhBZ5sPdBqOqSQbn/m3XyIw8DsZtvEEs9KoiXyz5T7X7IgFXtvcty3gtNW0xugtjyP9SAr5zy15jW1PAFFFrfRIO4nOkIAQ7UmuaVaYCw5uWxFmBknSxhaPfRT9dh56RalvdyLNcBdKQReZn9XnMlwHnQOC98KEU0lIgUnSmnwXHPsD8oU1tvV+mFBUSydHWO4L4Hsd6GBLyga5rAGj4uhngXoD2N1ovHbczIqWGgZ/jCaqXQjk1iFDN9lnb88FDMmhVl32aBxynaEcWIq4LkAlZ1y7U6gD3uRJuxDuEFdXoejobYd2n6B3OPybsfjcT55MdT3vCqMXbRMuSjeYoI2FmeOG0d5N9QjKRuV/N6vIYEqAZL/uMwam9uQMUU3FxCDfJU3uhfNQeZFGVcNgKySAfpMBO3/Cfjj00xxMjeRKrAGs9IhdYi8D1Rz5es3a7vpDnd4taiahlxx43jEBFX7fdjGh5Q8m5SovIIkN6c/d5vojl4+JsrlKonsk4lN0IcNKz+NiiGcoUBcUSbQMVq2bIeYZ4nDOUPraZ8Fl6w4Fr1neWLELgfc76ni2LojxKjzP43W+RFBgdkQ+LSkk/3oHlA7Snz7V+hSwIdIsBx+dIgBSzxYwM6gZB+lNt52xbE/QtRkxeVC/ywAXqQUqaFJ7iAtwmYYFLmXR0RiKYFb+IszBoNkxj3k7f7ngrRbF99g05eLxsCGfcYhHZGo+pgOnQvAgAvijas7VZKS5LI9HPlR/QFxFwRehTB7HgNu+qxTlx5skQrlMR7SWkXkh2vHOLcry1aypmLCSC+A84aoscuJRRTzHXlpeWPTbJo
  template:
    metadata:
      name: solutio-db
      namespace: solutio-prod
    type: Opaque
