---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: solutio-auth
  namespace: solutio-prod
spec:
  encryptedData:
    BETTER_AUTH_SECRET: AgBd5YX0lXUoYT0UgaxSWCetbWBiUxUCTqVwiQxjrp6cnVOc9hE/MH5cTvKjFaRbi0nCVO2r6+Yt1k3WAiB/TcRljtF9EjPb6Knh83Rr+Iwu86zg7spxkWzAlLICKztUJat6h7pq+0GqsuGmvr9iMWe5hrqR3USbjCkZCvRmmKGk9DP+nTiikfjrEjH7smoigyQx9uBTbcELAqCE4vRMMnok/kCwsjX+kCvr8ptHkViHgMC10O2kSQRGnRL8b9js7vaj7GL9h64BAQPSdfg1TxXz7m97BUf/edYIo5tM/0xpkaZxBnsK0PC5u5J6636tqVqayVN5yM4w75e2Sb6YKAj+eppQ80KIyYHwXOQcNqogxv8bxnQ6eNGsZmZ4l2KfVVvRMHG1ltlt8ZtbIOs56g5zkMqP50ot65RulBg62C4S8vVcBys61MiL3CHoO5ul3RmCLZW2DjzzLUFiN3bgC1BomzdE0DjsPR+orqZO5R3UbxbAs3gKpoQHXxBLPMi1mL/AyqR/nCowctrpQycY7/YzAuqyNgZOCn7MrLEFzOq/dJam5+ZAxze3cvNcvu6ko19rt4gmsP5wkRqI/3JCqKCwuEpC8tbdVojYu4C8tquiBe8BoBDxvZhPKt0j/CKbVDPB2iunTps2kUkhCgf9IOKJxfc0q/Rngpwrfu4ZsJPnMiEfRFAQUjMDzAaDxYEPnCHLw6UZAfuiNcB2va8CDX+dWW8upZeYw4XFg85FNeWcOad+Ul5CsKAWfI5JJejdFJQ1CMP4Ke1Ps6U08OElsCBk
    BETTER_AUTH_URL: AgBpq6BNvR4wHD/WmjKBtk9i4E9GdTOYzcgSAx+P6GDocIXNW1k5PLH5AshDMn7fBVs5VmOEw59PEsaeetKt9er5Uey+uoYYWaRDPUx6hO59BQGrizFg2pFEDaTdTwGX8e12g63sgpH+tI5eOjtr4KzDILCRR/+2kOXgSxU6urPejDXZCeYojUTb5exNmFp5Ql/jVAWk9LdqR76+6gQaXyfCZuNk3Wr5LJZ/PvrxKk8izfICtVdnrbrJFXVCKG/cctJsmd/TOTOyDvEavCJ42cDmYaC92bS6W8lMqSs34tnz0jWeAPum1S+M6aN0hbZP26ecwA6g2uVyFUoSZlmVpMsB/A0N+D15Yp5ZiJkGChzr4iwJkZUG2lKo7JLVO2Cns+JoTSR6ui1rMsc5eKDbHWEHBamCtq+NiiwN+prNuTEs3JXOSomZ5ZN305Mt72yMU67h37mZCUAQbKQDeyJwm+3KBp29XqbUuSsZ0Rg5qYSS8ot9fvJR9GML0Ab9plRXYbypI3mlS2odXHZ9l6rVAKbxr745vyAD4QjpAfsh2tCHsPwwIa+i8kESvevpfGJ4EejZc0Zc+HBiWvjk6GHNts3L1fICOxtTwnyLKIUIr6tHDt5tmJDe9+cc4yVje3RI2ibiwMT3vPXlTSLEf4TuOm+6CDnEDzWX1HP6rinjL1gOr/gBL4vKfVN+44g7XFPQrnqSZVD3C/N3ZCy6hhKZNMB69iJo3KxzBUGUGw8rXb8pKwg=
  template:
    metadata:
      name: solutio-auth
      namespace: solutio-prod
    type: Opaque
